SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/122 --marker shoremap/122/1_converted_variant.txt --consen shoremap/122/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/128 --marker shoremap/128/1_converted_variant.txt --consen shoremap/128/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/16 --marker shoremap/16/1_converted_variant.txt --consen shoremap/16/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/182 --marker shoremap/182/1_converted_variant.txt --consen shoremap/182/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/1 --marker shoremap/1/1_converted_variant.txt --consen shoremap/1/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/20 --marker shoremap/20/1_converted_variant.txt --consen shoremap/20/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/214 --marker shoremap/214/1_converted_variant.txt --consen shoremap/214/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/23 --marker shoremap/23/1_converted_variant.txt --consen shoremap/23/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/2 --marker shoremap/2/1_converted_variant.txt --consen shoremap/2/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/40 --marker shoremap/40/1_converted_variant.txt --consen shoremap/40/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/45 --marker shoremap/45/1_converted_variant.txt --consen shoremap/45/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/56 --marker shoremap/56/1_converted_variant.txt --consen shoremap/56/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/98 --marker shoremap/98/1_converted_variant.txt --consen shoremap/98/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/9 --marker shoremap/9/1_converted_variant.txt --consen shoremap/9/1_converted_consen.txt -verbose &
SHOREmap extract --chrsizes tair10.chrom.sizes --folder shoremap/raptor1 --marker shoremap/raptor1/1_converted_variant.txt --consen shoremap/raptor1/1_converted_consen.txt -verbose &
